#!/bin/bash
help() {
  printf "Usage: infa -\033[32m<1stargument>\033[0m \033[0;31m<2ndargument>\033[0m\n-\033[32md\033[0m Download InfaScripts\n-\033[32ms\033[0m Starts InfaScripts\n-\033[32mu\033[0m Update InfaScripts\n-\033[32mr\033[0m Remove InfaScripts\n-\033[32mh\033[0m Help\n-\033[32mc\033[0m Contacts   \033[0;31mi\033[0m Open InfamousMick tg link
              \033[0;31mr\033[0m Open Ravindu Deshan tg link
              \033[0;31mI\033[0m Open InfaChannel tg link
              \033[0;31mR\033[0m Open Samsung & Android Tweaks tg link\n"
  exit 1
}

# Verifica se sono stati forniti argomenti
if [ "$#" -eq 0 ]; then
  help
elif [ "$1" == "-d" ]; then
  rm -rf $HOME/infaScript > /dev/null 2>&1
  rm setup.sh ; wget https://raw.githubusercontent.com/Infamousmick/infaScript/Newpc/setup.sh > /dev/null 2>&1 ; bash setup.sh
elif [ "$1" == "-s" ]; then
  cd $HOME/infaScript
  bash run.sh
elif [ "$1" == "-u" ]; then
  rm setup.sh ; wget https://raw.githubusercontent.com/Infamousmick/infaScript/Newpc/setup.sh > /dev/null 2>&1 ; bash setup.sh
elif [ "$1" == "-r" ]; then
  rm $HOME/setup.sh
  rm -rf $HOME/infaScript
  echo "InfaScript removed"
elif [ "$1" == "-h" ]; then
  help
elif [ "$1" == "-c" ] && [ "$#" -ge 2 ]; then
  if [ "$2" == "i" ]; then
    link="https://t.me/InfamousMick"
    xdg-open "$link" || gnome-open "$link" || kde-open "$link" || x-www-browser "$link" || sensible-browser "$link"
  elif [ "$2" == "r" ]; then
    link="https://t.me/Ravindu_Deshan"
    xdg-open "$link" || gnome-open "$link" || kde-open "$link" || x-www-browser "$link" || sensible-browser "$link"
  elif  [ "$2" == "I" ]; then
    link="https://t.me/Infachannel_erendesu1"
    xdg-open "$link" || gnome-open "$link" || kde-open "$link" || x-www-browser "$link" || sensible-browser "$link"
  elif  [ "$2" == "R" ]; then
    link="https://t.me/SamsungTweaks"
    xdg-open "$link" || gnome-open "$link" || kde-open "$link" || x-www-browser "$link" || sensible-browser "$link"
  else
    help
  fi
else
  help
fi