#!/bin/bash
WDIR=$(pwd)
source $HOME/infaScript/res/colors
RISH=$HOME/infaScript/bin/rish

help() {
  printf "Usage: infa -${GREEN}<1stargument>${RESET} ${RED}<2ndargument>${RESET}\n-${GREEN}d${RESET} Download InfaScripts\n-${GREEN}s${RESET} Starts InfaScripts\n-${GREEN}u${RESET} Update InfaScripts\n-${GREEN}r${RESET} Remove InfaScripts\n-${GREEN}h${RESET} Help\n-${GREEN}c${RESET} Contacts   ${RED}i${RESET} Open InfamousMick tg link
              ${RED}r${RESET} Open Ravindu Deshan tg link
              ${RED}I${RESET} Open InfaChannel tg link
              ${RED}R${RESET} Open Samsung & Android Tweaks tg link\n"
  exit 1
}

confirm() {
  printf "${BLUE}Are you sure? (Y/n): ${RESET}"
  read -n 1 choice
  echo
  case "$choice" in
    y|Y) return 0 ;;
    n|N) exit 0 ;;
    *) confirm ;;
  esac
}

# Verifica se sono stati forniti argomenti
if [ "$#" -eq 0 ]; then
  help
elif [ "$1" == "-d" ]; then
  confirm
  apt update -y
  echo -e "\n"
  apt install wget git tsu -y
  echo -e "\n"
  rm -rf $HOME/infaScript > /dev/null 2>&1
  curl -sSL https://raw.githubusercontent.com/Infamousmick/infaScript/NewTermux/setup.sh | bash
elif [ "$1" == "-s" ]; then
  confirm
  cd $HOME/infaScript
  bash run.sh
elif [ "$1" == "-u" ]; then
  confirm
  cd $HOME/infaScript
  echo -e "\n[i] Make sure you have connected to the internet.\n"
  sleep 2
  echo -e "\n" ; git fetch origin ; git stash ; git rebase NewTermux ; echo -e "\n" ; git pull origin NewTermux ; echo -e "\n"
  chmod +x -R *
elif [ "$1" == "-r" ]; then
  confirm
  rm -rf $HOME/infaScript
  echo "InfaScript removed"
elif [ "$1" == "-h" ]; then
  help
elif [ "$1" == "-c" ] && [ "$#" -ge 2 ]; then
  if [ "$2" == "i" ]; then
    link="https://t.me/InfamousMick"
    xdg-open "$link"
  elif [ "$2" == "r" ]; then
    link="https://t.me/Ravindu_Deshan"
    xdg-open "$link"
  elif  [ "$2" == "I" ]; then
    link="https://t.me/Infachannel_erendesu1"
    xdg-open "$link"
  elif  [ "$2" == "R" ]; then
    link="https://t.me/SamsungTweaks"
    xdg-open "$link"
  else
    help
  fi
else
  help
fi